INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(1, 'Keno', 'Ma dobar', 'Vraca') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(2, 'Luca', 'Idiot', 'Trudi se') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(3, 'Component', 'Add component', 'In progress') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(4, 'Keno', 'Ma dobar', 'Vraca') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(5, 'Luca', 'Idiot', 'Trudi se') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(6, 'Component', 'Add component', 'In progress') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(7, 'Keno', 'Ma dobar', 'Vraca') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(8, 'Luca', 'Idiot', 'Trudi se') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(9, 'Component', 'Add component', 'In progress') RETURNING "id", "name", "description", "addr_140";
INSERT INTO "public"."tasks"("id", "name", "description", "addr_199") VALUES(10, 'Component', 'Add component', 'In progress') RETURNING "id", "name", "description", "addr_140";
